# LISTA 10 -  LIBRERÍA NUMPY

## <ins>Ejercicios Obligatorios </ins>

## EJERCICIO 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

In [16]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])

print(a.ndim)
print(a.shape)
print(a)

b=np.reshape(a,(3,3))

print(b.ndim)
print(b.shape)
print(b)

1
(9,)
[1 2 3 4 5 6 7 8 9]
2
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## EJERCICIO 2

Dados los arrays 2D ```[[-6, 5], [-4, 3], [-2, 1]] y [[1, 2], [3, 4], [5, 6]]```, concaténalos de modo que obtengas el array ```[[1, 2, -6, -5], [3, 4, -4, -3], [5, 6, -2, -1]]```

In [21]:
import numpy as np
a = np.array([[-6, 5], [-4, 3], [-2, 1]])
b = np.array([[1, 2], [3, 4], [5, 6]])

c= np.concatenate((a, b), axis=1)

print(c)

[[-6  5  1  2]
 [-4  3  3  4]
 [-2  1  5  6]]


## EJERCICIO 3

Dado el array 2D ```[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]```, busca las palabras que sean palíndromos. Necesitarás una función universal.

In [26]:
import numpy as np

a = np.array([["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]])

def es_palindromo(w):
    w = w.lower()
    n = len(w)
    for c in range(int(n / 2)):
        if w[c] != w[n - (c + 1)]:
            return False
    return True

np_es_palindromo = np.frompyfunc(es_palindromo, 1, 1)
print(a[np_es_palindromo(a) == True])

indices=np.where(np_es_palindromo(a)==True)
for i in range(len(indices[0])):
    print(a[indices[0][i]][indices[1][i]])



## EJERCICIO 4

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase “¡Has fallado! ¡Prueba otra vez!”

In [30]:
from numpy import random

encontrado=False
numAle=random.randint(1, 10)
numIntentos=0

while encontrado==False:
    numUsu=int(input("Introduzca un numero al azar entre 1 y 10 a ver si acierta:"))
    
    if numUsu==numAle:
        encontrado=True
        numIntentos+=1
        print("¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}".format(numAle))
    else:
        print("¡Has fallado! ¡Prueba otra vez!")
        numIntentos+=1
        
print("El número de intentos para acertar ha sido {}".format(numIntentos))

Introduzca un numero al azar entre 1 y 10 a ver si acierta: 2


¡Has fallado! ¡Prueba otra vez!


Introduzca un numero al azar entre 1 y 10 a ver si acierta: 3


¡Has fallado! ¡Prueba otra vez!


Introduzca un numero al azar entre 1 y 10 a ver si acierta: 4


¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 4
El número de intentos para acertar ha sido 3


## EJERCICIO 5

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

In [37]:
import numpy as np
numerosSecretos=np.random.randint(0,20,5)
print(numerosSecretos)

ordenados=0

while ordenados<5:
    acertados=0
    
    for i in range(5):
        num=int(input("Introduce el numero de la posición {}: ".format(i)))
        if num in numerosSecretos:
            acertados+=1
        if numerosSecretos[i]==num:
            ordenados+=1   
    print("Has acertado: ", acertados)
    print("Están en el ordena adecuado: ", ordenados)
print("¡¡¡ENHORABUENA!!! Has acertado el array que había pensado:", numerosSecretos)

[14  4 11  4 19]


Introduce el numero de la posición 0:  14
Introduce el numero de la posición 1:  4
Introduce el numero de la posición 2:  11
Introduce el numero de la posición 3:  4
Introduce el numero de la posición 4:  19


Has acertado:  5
Están en el ordena adecuado:  5
¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: [14  4 11  4 19]


## EJERCICIO 6

A partir de la lista ```[-3, -2, -1, 0, 1, 2, 3]```, genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

In [40]:
import numpy as np
a = np.array([-3, -2, -1, 0, 1, 2, 3])
c1=np.random.choice(a, size = (3, 4))
c2=np.random.choice(a, size = (3, 4))
print(c1)
print(c2)
print(c1+c2)

[[-2  0 -3 -1]
 [ 2  0 -2  1]
 [ 1 -1  2  3]]
[[ 2  3  2  2]
 [-2 -1 -2  3]
 [ 1  0 -2  2]]
[[ 0  3 -1  1]
 [ 0 -1 -4  4]
 [ 2 -1  0  5]]


## <ins>Ejercicios Opcionales </ins>

## EJERCICIO 7

Dado el array 2D ```[[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]``` divídelo en 3 arrays 2D.

In [ ]:
import numpy as np
a = np.array([[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])
b1,b2,b3=np.split(a,3)
print("b1: ", b1)
print("b2: ", b2)
print("b3: ", b3)

b1:  [[ 1  2  3]
 [-1  0  1]]
b2:  [[ 4  5  6]
 [-4  0  4]]
b3:  [[ 3  2  1]
 [-3  0  3]]


## EJERCICIO 8

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.

In [ ]:
import numpy as np
a = np.array(["ala", "delfín", "arroz"])

def numVocales(w):
    contador=0
    w = w.lower()
    for c in w:
        if c in "aeiou":
            contador+=1
    return contador

vocales=0
for palabra in a:
    vocales=vocales+numVocales(palabra)
    
print("El numero de vocales es: {}".format(vocales))

El numero de vocales es: 5
