# LISTA 10 -  LIBRERÍA NUMPY

## <ins>Ejercicios Obligatorios </ins>

## EJERCICIO 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

In [2]:
import numpy as np

a = np.arange(9)

print(a)

b=np.split(a, 3,  axis=0)
print(b)
array_3d = a.reshape((3, 3, 1))
print(array_3d)


[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]


## EJERCICIO 2

Dados los arrays 2D ```[[-6, 5], [-4, 3], [-2, 1]] y [[1, 2], [3, 4], [5, 6]]```, concaténalos de modo que obtengas el array ```[[1, 2, -6, -5], [3, 4, -4, -3], [5, 6, -2, -1]]```

In [35]:
a1=[[-6, 5],[-4, 3],[-2, 1]]
a2=[[1, 2],[3, 4],[5, 6]]
a3=np.concatenate((a2,a1), axis=1)
print(a3)

[[ 1  2 -6  5]
 [ 3  4 -4  3]
 [ 5  6 -2  1]]


## EJERCICIO 3

Dado el array 2D ```[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]```, busca las palabras que sean palíndromos. Necesitarás una función universal.

In [13]:
array2d=[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]


def es_palindromo(palabra):
    if(palabra== palabra[::-1]):
        return palabra
    return ""

palindromos = np.frompyfunc(es_palindromo, 1, 1) 

print(palindromos(array2d))

[['ala' '' '']
 ['' 'kayak' '']
 ['' '' 'elle']]


## EJERCICIO 4

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase “¡Has fallado! ¡Prueba otra vez!”

In [44]:
num=np.random.randint(1,11)
print(num)
guess=0
intento=1
while(guess!=num):
    guess=int(input(f"Intenta acertar un numero del 1 al 10"))
    if(guess!=num):
        intento+=1
        print(f"Has fallado! ¡Prueba otra vez!")
        
print(f"¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {num} y el numero de intentos son {intento}")

5
Has fallado! ¡Prueba otra vez!
Has fallado! ¡Prueba otra vez!
Has fallado! ¡Prueba otra vez!
Has fallado! ¡Prueba otra vez!
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 5 y el numero de intentos son 5


## EJERCICIO 5

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

In [3]:
import numpy as np
arr1d =np.array([np.random.randint(1, 21) for _ in range(5)])
print(arr1d)

resp =np.array([int(input("Introduce un número: ")) for _ in range(5)])

while not (arr1d==resp).all():
    sumatorioLugar=0
    sumatorioNumero=0
    for i in range(len(arr1d)):
        if(resp[i] in arr1d):
            sumatorioNumero+=1
            if(arr1d[i]==resp[i]):
                sumatorioLugar+=1                  
    print(f"Has acertado {sumatorioLugar} lugares y {sumatorioNumero} numeros")
    resp =np.array([int(input("Introduce un número: ")) for _ in range(5)])
print(f"¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {arr1d} !!!")



[ 8  6  8 15 11]
Has acertado 0 lugares y 0 numeros
Has acertado 0 lugares y 4 numeros
Has acertado 0 lugares y 5 numeros
¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: [ 8  6  8 15 11] !!!


## EJERCICIO 6

A partir de la lista ```[-3, -2, -1, 0, 1, 2, 3]```, genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

In [170]:
a=[-3, -2, -1, 0, 1, 2, 3]
b = np.random.choice(a,size=(3,4))
c = np.random.choice(a,size=(3,4))
d=np.add(b,c)
print(d)

[[-3  0  4 -3]
 [ 0  2  2 -2]
 [ 1  0  0  3]]


## <ins>Ejercicios Opcionales </ins>

## EJERCICIO 7

Dado el array 2D ```[[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]``` divídelo en 3 arrays 2D.

## EJERCICIO 8

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.